### PR TITLE
Adds link for conventional comments

### LINKED ISSUE #107: Label comments and add a section to introduce the labels
**Is your feature request related to a problem? Please describe.**
We discussed how to provide feedback during code review in one of the FIMS project meetings. Labeling comments during code review could potentially save hours of communications and misunderstandings. Comments with labels are parseable by machines. They are also helpful for labeling the severity of the comments, differentiating required changes from suggestions (see [Google Engineering Practices Documentation](https://google.github.io/eng-practices/review/reviewer/comments.html#label-comment-severity)). 

**Describe the solution you'd like**
- Encourage reviewers to use all or some of the labels from [conventionalcomments.org](https://conventionalcomments.org/). [Edited] For example, praise, ~~nitpick~~ quibble, suggestion with _blocking_ or _non-blocking_ **decorations**, question, and thought.
- Use decorations to give additional context for a comment and help authors to prioritize comments/tasks. For example, A comment with _non-blocking_ **decoration** should not prevent the subject under review from being accepted. A comment with _blocking_ **decoration** should prevent the subject under review from being accepted, until it is resolved.
- Format of a comment
```
<label> [decorations]: <subject>
[discussion]
```
```
- label - This is a single label that signifies what kind of comment is being left.
- subject - This is the main message of the comment.
- decorations (optional) - These are extra decorating labels for the comment. They are surrounded by parentheses and comma-separated.
- discussion (optional) - This contains supporting statements, context, reasoning, and anything else to help communicate the “why” and “next steps” for resolving the comment.
```
Document labels, decorations and format in the collaboration workflow book.

**Describe alternatives you've considered**
Too much work :sleepy: Let's not label comments.

**Additional context**
NA

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
# What is the feature?
* Add link to how to use conventional commit messages
* As well as removes broken link to Review section.

# How have you implemented the solution?
* 

# Does the PR impact any other area of the project, maybe another repo?
* N/A

Close #107

### CODE REVIEW

**Review by Bai-Li-NOAA — APPROVED** [review]
Looks good! Do we want to include those guides in the FIMS [`pr-checklist.yml`](https://github.com/NOAA-FIMS/FIMS/blob/main/.github/workflows/pr-checklist.yml) as well?

**Comment by kellijohnson-NOAA** [comment]
Thanks for the suggestion @Bai-Li-NOAA. Do you think that we should just eliminate this section from the collaborative workflow guide and put the link in the GitHub action that you referenced above. By "this section", I mean the following
image

**Comment by Bai-Li-NOAA** [comment]
@kellijohnson-NOAA, that sounds like a good plan to me. I also noticed that some links (e.g., Code Review link in the image) are not working. Maybe we can add a GHA (e.g., [Linkspector](https://github.com/UmbrellaDocs/linkspector)) to check for broken links.

**Comment by kellijohnson-NOAA** [comment]
Okay, two new issues have been created one to have the links tested and one to create the link to conventional commits in FIMS. Finally, a force push with the relevant section removed is now the content of this PR. As soon as the tests pass I will merge it in.

**Pull request merged**
