### PR TITLE
Refactor: Remove issue templates that are now in .github repo

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
# What is the feature?
* Moves PR and issue templates to NOAA-FIMS/.github/.github so they are available to all repositories within NOAA-FIMS.

# How have you implemented the solution?
Moved the files to NOAA-FIMS/.github/.github see https://github.com/NOAA-FIMS/.github/commit/33c261d for the exact commit.

# Does the PR impact any other area of the project?
One template, handbook_addition.md was left as is.

# How to test this change
Go to another repository in FIMS and see the available issue templates 🤯 or see below
image

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

### CODE REVIEW

**Review by Bai-Li-NOAA — APPROVED** [review]
Thanks for removing the templates.

There is a syntax error in the `feature_request.yml` inthe .github repo, which does not appear in your snapshot or available issue templates in other repos. I will report this issue on the .github repo.

**Comment by kellijohnson-NOAA** [comment]
Thanks @Bai-Li-NOAA!

**Comment by kellijohnson-NOAA** [comment]
@Bai-Li-NOAA I just found out that the issue templates in .github will not work in this repository unless we delete the entire folder, i.e., delete NOAA-FIMS/collaborative_workflow/.github/ISSUE_TEMPLATE, and thus, we need to decide if the `[handbook-addition.md](https://github.com/NOAA-FIMS/collaborative_workflow/blob/main/.github/ISSUE_TEMPLATE/handbook-addition.md)` is worth migrating over to the .github repository, which would make it show up in every repository or if we should delete this pull request?

**Comment by iantaylor-NOAA** [comment]
I vote to delete https://github.com/NOAA-FIMS/collaborative_workflow/blob/main/.github/ISSUE_TEMPLATE/handbook-addition.md as it doesn't add much and we can easily create handbook addition issues from a blank issue easily enough now that we've been developing the handbook for a while.

**Pull request merged**
